apiVersion: v1
kind: Service
metadata:
  name: express-app-service
  labels:
    app: express-app-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: express-app
